namespace MyHomePage.Models;

/// <summary>
/// Weekly coach report — a structured summary of the athlete's last seven
/// days, generated by the AI assistant from the durable
/// <see cref="TrainingStats"/> snapshot. Persisted one file per ISO week
/// so reports can be re-read without re-calling the API.
/// </summary>
public sealed record CoachReport
{
    /// <summary>ISO week identifier (e.g. <c>2026-W20</c>) used as the file key.</summary>
    public string IsoWeek { get; init; } = string.Empty;

    /// <summary>UTC start of the period the report covers (inclusive).</summary>
    public DateTime WeekStartUtc { get; init; }

    /// <summary>UTC end of the period the report covers (inclusive).</summary>
    public DateTime WeekEndUtc { get; init; }

    /// <summary>UTC timestamp when the report was generated.</summary>
    public DateTime GeneratedAtUtc { get; init; }

    /// <summary>
    /// Name of the AI model that produced the report — kept so old reports
    /// remain traceable when the default model is rotated.
    /// </summary>
    public string Model { get; init; } = string.Empty;

    /// <summary>One-sentence headline that captures the week.</summary>
    public string Headline { get; init; } = string.Empty;

    /// <summary>
    /// Two- or three-paragraph narrative analysing the week (volume, load,
    /// notable sessions, comparisons to recent weeks). Plain text, not
    /// Markdown, so it can be rendered into any UI shell without parsing.
    /// </summary>
    public string Narrative { get; init; } = string.Empty;

    /// <summary>Bullet-point highlights that deserved a callout.</summary>
    public IReadOnlyList<string> Highlights { get; init; } = Array.Empty<string>();

    /// <summary>Cautions / red flags the athlete should watch for.</summary>
    public IReadOnlyList<string> Concerns { get; init; } = Array.Empty<string>();

    /// <summary>Suggested focus areas for the upcoming week.</summary>
    public IReadOnlyList<string> NextWeekFocus { get; init; } = Array.Empty<string>();

    /// <summary>Compact list of key numerical metrics shown alongside the narrative.</summary>
    public IReadOnlyList<CoachKeyMetric> KeyMetrics { get; init; } = Array.Empty<CoachKeyMetric>();
}

/// <summary>One row in the report's key-metrics list — a label + value pair.</summary>
public sealed record CoachKeyMetric
{
    /// <summary>Short metric label (e.g. "Total distance").</summary>
    public string Label { get; init; } = string.Empty;

    /// <summary>Formatted value (e.g. "42.5 km").</summary>
    public string Value { get; init; } = string.Empty;
}
